### PR TITLE
Fix cache error

### LINKED ISSUE #71: internal error:test-icache.cc：line 163、118、188
**Describe the bug**
Run test case failed

**To Reproduce**
1. Build with options 'riscv64.native.release'
2. Run test/program 'python2 ./tools/run-tests.py --outdir=./ cctest' on `hifive unleashed`
3. See error

**Expected behavior**
not error occurs

**Errors/Logs**
```
=== cctest/test-icache/TestFlushICacheOfExecutable ===
#
# Fatal error in ../../test/cctest/test-icache.cc, line 163
# Check failed: 23 == f.Call(23) (23 vs. 87).
#
#
#
#FailureMessage Object: 0x3fffe06c88
=== cctest/test-icache/TestFlushICacheOfWritable ===
#
# Fatal error in ../../test/cctest/test-icache.cc, line 118
# Check failed: 23 == f.Call(23) (23 vs. 71).
#
#
#
#FailureMessage Object: 0x3fff9fbc88
=== cctest/test-icache/TestFlushICacheOfWritableAndExecutable ===
#
# Fatal error in ../../test/cctest/test-icache.cc, line 188
# Check failed: 23 == f.Call(23) (23 vs. 91).
#
#
#
#FailureMessage Object: 0x3fffe09c78
```

**Additional context**
None

### PR DESCRIPTION
**Pull request by luyahan**
Fix #71 :In riscv64, should use `fence.i` to synchronize the instruction and data streams. Refer to `The RISC-V Instruction Set Manual
Volume I: Unprivileged ISA.`

### CODE REVIEW

**Comment by fw-brice** [comment]
That change was added earlier by @palmer-dabbelt with the comment:

> I know the ISA manual says fence.i in it, and that the older versions say it's
> in I, but it's not and you can't use it from userspace in Linux (at least, if
> you want your programs to work). It's currently implemented as a system call,
> but as there may eventually be something faster you should use the GCC builtin
> instead.

**Comment by luyahan** [comment]
> That change was added earlier by @palmer-dabbelt with the comment:
> 
> > I know the ISA manual says fence.i in it, and that the older versions say it's
> > in I, but it's not and you can't use it from userspace in Linux (at least, if
> > you want your programs to work). It's currently implemented as a system call,
> > but as there may eventually be something faster you should use the GCC builtin
> > instead.
> 
> See #26

GCC builtin `butilin_clear_cache` in hifive unleashed is useless, i don't know why it .I can't find source of `butilin_clear_cache` .
So i replace it with asm"fence.i"

**Comment by fw-brice** [comment]
> GCC builtin `butilin_clear_cache` in hifive unleashed is useless. i don't know why . I can't find source of `butilin_clear_cache` .
> So i replace it with asm"fence.i"

Ok, so then let's leave that `builtin_clear_cache` there but commented out and add a FIXME comment so we remember to come back to it later.

**Comment by luyahan** [comment]
@fw-brice  i have add a FIXME comment .

File: src/codegen/riscv64/cpu-riscv64.cc [hunk 1]
```diff
@@ -16,7 +16,8 @@ namespace internal {
 
 void CpuFeatures::FlushICache(void* start, size_t size) {
 #if !defined(USE_SIMULATOR)
-  __builtin___clear_cache(start, (char *)start + size);
+   //FIXME:builtin_clear_cache don't work, so replace it with 'fence.i'.
```
Comment (fw-brice) [inline src/codegen/riscv64/cpu-riscv64.cc:19]: To keep a consistent style, making it easier to find our fixmes, please change this to:
```
  // FIXME(RISCV): builtin_clear_cache doesn't work yet, so use `fence.i` for now
  // __builtin___clear_cache(start, (char *)start + size);
```

Comment (luyahan) [reply src/codegen/riscv64/cpu-riscv64.cc]: Thank you for your advice. I have fixed it.

**Comment by fw-brice** [comment]
I tried running the tests locally since the CI job is failing and I see an error on `cctest/test-cpu-profiler/CrossScriptInliningCallerLineNumbers`. Do you see that @yahan?

**Comment by fw-brice** [comment]
> I tried running the tests locally since the CI job is failing and I see an error on `cctest/test-cpu-profiler/CrossScriptInliningCallerLineNumbers`. Do you see that @YaHan?

Actually, if I run it individually, it passes. I am not sure yet why.

**Comment by penguinwu** [comment]
I've seen this test failing intermittently on my local runs. If running individually, it also fails from time to time. This test does not seem to be stable. I think we shall skip it.
