### PR TITLE
fix-75 atomic

### LINKED ISSUE #75: internal error: cctest/test-run-wasm-atomic
**Describe the bug**
Run test case failed

**To Reproduce**
1. Build with options 'riscv64.native.release'
2. Run test/program 'python2 ./tools/run-tests.py --outdir=./ cctest' on `hifive unleashed`
3. See error

**Expected behavior**
not error occurs

**Errors/Logs**
```
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicAdd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 1403684).
#
#
#
#FailureMessage Object: 0x3fffea0928
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicAdd16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 52163).
#
#
#
#FailureMessage Object: 0x3fffe0c978
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicAdd8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 85
# Check failed: initial == r.Call(j) ('\0' vs. 46).
#
#
#
#FailureMessage Object: 0x3fff9d4988
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicAnd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffa96928
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicCompareExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 113
# Check failed: initial == r.Call(i, j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fffdd78f8
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicAnd8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 85
# Check failed: initial == r.Call(j) (\x1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fff84a988
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicAnd16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffbf7978
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicCompareExchange8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 156
# Check failed: initial == r.Call(i, j) ('\0' vs. 1).
#
#
#
#FailureMessage Object: 0x3fff9e8978
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicCompareExchange16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 135
# Check failed: initial == r.Call(i, j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fff88e8f8
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fffbfa918
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicExchange16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fffc0c978
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicExchange8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 85
# Check failed: initial == r.Call(j) ('\0' vs. 1).
#
#
#
#FailureMessage Object: 0x3ffffd5978
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicOr ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fff88f928
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicOr16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fff932988
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicOr8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 87
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (\x1 vs. '\0').
#
#
#
#FailureMessage Object: 0x3fffc57988
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicSub8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 87
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (\xff vs. '\0').
#
#
#
#FailureMessage Object: 0x3fffaf4988
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicSub ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 4293747064).
#
#
#
#FailureMessage Object: 0x3fffa50928
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicSub16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 43774).
#
#
#
#FailureMessage Object: 0x3fffd0a978
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicStoreParameter ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 304
# Check failed: 10 == r.Call(10) (10 vs. 4522580).
#
#
#
#FailureMessage Object: 0x3fffeda9c8
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicXor16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fff984978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicAdd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 4276534).
#
#
#
#FailureMessage Object: 0x3fffb14928
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicXor ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fff913928
=== cctest/test-run-wasm-atomics/RunWasmLiftoff_I32AtomicXor8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 87
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (\x1 vs. '\0').
#
#
#
#FailureMessage Object: 0x3fffb7f988
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicAdd8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 85
# Check failed: initial == r.Call(j) ('\0' vs. 120).
#
#
#
#FailureMessage Object: 0x3fffb7b978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicAdd16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 31525).
#
#
#
#FailureMessage Object: 0x3fff8a3978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicAnd16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffa0b978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicAnd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (1 vs. 0).
#
#
#
#FailureMessage Object: 0x3ffff2c928
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicCompareExchange16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 135
# Check failed: initial == r.Call(i, j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fffeaf8f8
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicCompareExchange8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 156
# Check failed: initial == r.Call(i, j) ('\0' vs. 1).
#
#
#
#FailureMessage Object: 0x3fffeca978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicCompareExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 113
# Check failed: initial == r.Call(i, j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fff9de8f8
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicAnd8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 85
# Check failed: initial == r.Call(j) (\x1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffd4f978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicExchange16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fffe1c978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fffc81918
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicOr ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3ffff79928
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicOr8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 85
# Check failed: initial == r.Call(j) ('\0' vs. 1).
#
#
#
#FailureMessage Object: 0x3fffa27988
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicExchange8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 85
# Check failed: initial == r.Call(j) ('\0' vs. 1).
#
#
#
#FailureMessage Object: 0x3fff9c4978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicOr16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3ffffd4978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicSub ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 4294936098).
#
#
#
#FailureMessage Object: 0x3fffdef928
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicSub16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 49247).
#
#
#
#FailureMessage Object: 0x3fff89d978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicStoreParameter ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 304
# Check failed: 10 == r.Call(10) (10 vs. 17535450).
#
#
#
#FailureMessage Object: 0x3ffff399c8
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicSub8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 87
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (\xff vs. '\0').
#
#
#
#FailureMessage Object: 0x3ffff53978
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicXor ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 30
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffdb5928
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicXor16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fffcc3978
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAdd16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 86
# Check failed: initial == r.Call(j) (0 vs. 65010).
#
#
#
#FailureMessage Object: 0x3fffd65998
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAdd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 1157974).
#
#
#
#FailureMessage Object: 0x3fffd24928
=== cctest/test-run-wasm-atomics/RunWasmTurbofan_I32AtomicXor8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics.cc, line 85
# Check failed: initial == r.Call(j) ('\0' vs. 1).
#
#
#
#FailureMessage Object: 0x3fffbb3978
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I32AtomicCompareExchange8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 206
# Check failed: initial == r.Call(i, j) ('\0' vs. 1).
#
#
#
#FailureMessage Object: 0x3fffc4f998
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAddConvertDrop ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 459
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (2459584641779389781 vs. 12297848147757808847).
#
#
#
#FailureMessage Object: 0x3fff9749b8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAdd8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 116
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (\x1 vs. '\0').
#
#
#
#FailureMessage Object: 0x3fff878998
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAddDrop ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 376
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (2459584641779389781 vs. 2459584641779339114).
#
#
#
#FailureMessage Object: 0x3ffffee9a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAdd32U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 57
# Check failed: initial == r.Call(j) (0 vs. 159828).
#
#
#
#FailureMessage Object: 0x3fff9c0918
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAddUseOnlyLowWord ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 737
# Check failed: 0x90abcdef == r.Call() (2427178479 vs. 2427669733).
#
#
#
#FailureMessage Object: 0x3fffc649b8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAnd16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 86
# Check failed: initial == r.Call(j) (1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffd89998
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAnd8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 114
# Check failed: initial == r.Call(j) (\x1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffa6c998
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAnd32U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 57
# Check failed: initial == r.Call(j) (1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffad4918
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicAnd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 28
# Check failed: initial == r.Call(j) (1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffb18928
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicCompareExchange32U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 164
# Check failed: initial == r.Call(i, j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fff88f8e8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicCompareExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 142
# Check failed: initial == r.Call(i, j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fffb328f8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicCompareExchange16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 186
# Check failed: initial == r.Call(i, j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3ffffbe988
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexAdd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 539
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 913123828).
#
#
#
#FailureMessage Object: 0x3ffffba9a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexAnd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 539
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 858980352).
#
#
#
#FailureMessage Object: 0x3fffb5e9a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexAddNarrow ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 540
# Check failed: static_cast<uint32_t>(op(initial, local)) == static_cast<uint32_t>(r.builder().ReadMemory(&memory[0])) (2863320268 vs. 858997828).
#
#
#
#FailureMessage Object: 0x3fffbc59a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexAndNarrow ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 540
# Check failed: static_cast<uint32_t>(op(initial, local)) == static_cast<uint32_t>(r.builder().ReadMemory(&memory[0])) (858980352 vs. 858997828).
#
#
#
#FailureMessage Object: 0x3fffab79a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexOrNarrow ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 540
# Check failed: static_cast<uint32_t>(op(initial, local)) == static_cast<uint32_t>(r.builder().ReadMemory(&memory[0])) (2004339916 vs. 858997828).
#
#
#
#FailureMessage Object: 0x3fffc729a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexExchangeNarrow ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 540
# Check failed: static_cast<uint32_t>(op(initial, local)) == static_cast<uint32_t>(r.builder().ReadMemory(&memory[0])) (2004322440 vs. 858997828).
#
#
#
#FailureMessage Object: 0x3fffec5998
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 539
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 2004322440).
#
#
#
#FailureMessage Object: 0x3ffff629a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexOr ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 539
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 2004339916).
#
#
#
#FailureMessage Object: 0x3fffd7c9a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexXor ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 539
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 1145359564).
#
#
#
#FailureMessage Object: 0x3fff8389a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexXorNarrow ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 540
# Check failed: static_cast<uint32_t>(op(initial, local)) == static_cast<uint32_t>(r.builder().ReadMemory(&memory[0])) (1145359564 vs. 858997828).
#
#
#
#FailureMessage Object: 0x3fffb189a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexSubNarrow ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 540
# Check failed: static_cast<uint32_t>(op(initial, local)) == static_cast<uint32_t>(r.builder().ReadMemory(&memory[0])) (3149642684 vs. 858997828).
#
#
#
#FailureMessage Object: 0x3fffa979a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConstIndexSub ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 539
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 3550054092).
#
#
#
#FailureMessage Object: 0x3ffffc69a8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConvertAnd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 493
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 286326784).
#
#
#
#FailureMessage Object: 0x3fff8ca9b8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConvertOr ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 493
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 859002197).
#
#
#
#FailureMessage Object: 0x3fffcd99b8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConvertExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 493
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 286331153).
#
#
#
#FailureMessage Object: 0x3fff9b79b8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConvertCompareExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 518
# Check failed: static_cast<uint32_t>(initial) == r.Call(initial, local) (858997828 vs. 286331153).
#
#
#
#FailureMessage Object: 0x3fffc33968
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConvertAdd ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 493
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 572657745).
#
#
#
#FailureMessage Object: 0x3fffbbe9b8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConvertXor ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 495
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (56294709024085 vs. 1229801703532086340).
#
#
#
#FailureMessage Object: 0x3fffc229b8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fff88a918
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicConvertSub ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 493
# Check failed: static_cast<uint32_t>(initial) == r.Call(local) (858997828 vs. 286349748).
#
#
#
#FailureMessage Object: 0x3ffff179b8
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicExchange16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 86
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fff929998
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicExchange8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 114
# Check failed: initial == r.Call(j) ('\0' vs. 1).
#
#
#
#FailureMessage Object: 0x3ffff28998
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicExchange32U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 59
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (1 vs. 0).
#
#
#
#FailureMessage Object: 0x3fffe05918
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicOr ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 28
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3fffadb928
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicNonConstIndexCompareExchangeNarrow ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 575
# Check failed: static_cast<uint16_t>(CompareExchange(initial, initial, local)) == static_cast<uint16_t>(r.builder().ReadMemory(&memory[0])) (26214 vs. 13879).
#
#
#
#FailureMessage Object: 0x3fffada958
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicOr16U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 86
# Check failed: initial == r.Call(j) (0 vs. 1).
#
#
#
#FailureMessage Object: 0x3ffff7f998
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicNonConstIndexCompareExchange ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 593
# Check failed: static_cast<uint32_t>(initial) == r.Call(initial, local) (4243535415 vs. 2004313702).
#
#
#
#FailureMessage Object: 0x3fffb48958
=== cctest/test-run-wasm-atomics64/RunWasmLiftoff_I64AtomicOr8U ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-atomics64.cc, line 116
# Check failed: expected == r.builder().ReadMemory(&memory[0]) (\x1 vs. '\0').
#
#
#
#FailureMessage Object: 0x3fffcd5998

```

**Additional context**

### PR DESCRIPTION
**Pull request by luyahan**
Fix #75:If the SC.[W] succeeds, the instruction writes the word in rs2 to memory, and
it writes zero to rd. If the SC.[W] fails, the instruction does not write to memory, and it writes a
nonzero value to rd.

### CODE REVIEW

**Comment by fw-brice** [comment]
Please fix the commit message. See https://github.com/v8-riscv/v8/wiki/using-git#committing

File: src/compiler/backend/riscv64/code-generator-riscv64.cc [hunk 1]
```diff
@@ -325,7 +325,7 @@ void EmitWordLoadPoisoningIfNeeded(CodeGenerator* codegen,
     __ bin_instr(i.TempRegister(1), i.OutputRegister(0),                       \
                  Operand(i.InputRegister(2)));                                 \
     __ store_conditional(i.TempRegister(1), MemOperand(i.TempRegister(0), 0)); \
-    __ BranchShort(&binop, eq, i.TempRegister(1), Operand(zero_reg));          \
+    __ BranchShort(&binop, ne, i.TempRegister(1), Operand(zero_reg));          \
```
Comment (fw-brice) [inline src/compiler/backend/riscv64/code-generator-riscv64.cc:328]: Please add a comment before each of these macros to explain what should happen. The code difficult to follow.

**Comment by DrRezaYazdani1** [comment]
The changes look fine to me
